### ISSUE TITLE
我尝试解决，没解决了，g2o版本的问题吗

### ISSUE THREAD

**Issue by HIT-Ygq** [chengwei0427/floam_g2o#1]
odomEstimationClass.cpp:115:76: error: no matching function for call to ‘g2o::BlockSolver<g2o::BlockSolverTraits<6, 1> >::BlockSolver(LinearSolverType*&)’
 BlockSolverType *blockSolver = new BlockSolverType(linearSolver);
 error: no matching function for call to ‘g2o::OptimizationAlgorithmGaussNewton::OptimizationAlgorithmGaussNewton(BlockSolverType*&)’
           auto solver = new g2o::OptimizationAlgorithmGaussNewton(blockSolver);

                                                                            ^

**Comment by chengwei0427** [comment]
抱歉，才看到；应该是g2o版本问题；不过相信你现在已经解决了。
